-- ============================================================
-- INVENTRIX - POSTGRESQL DATABASE SCHEMA
-- General-Purpose Inventory Management System
-- Database: PostgreSQL 16
-- ============================================================

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. SUPPLIERS TABLE
CREATE TABLE IF NOT EXISTS suppliers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150)    NOT NULL,
    contact_person  VARCHAR(100),
    phone           VARCHAR(25),
    email           VARCHAR(120),
    address         TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                 VARCHAR(50)     NOT NULL UNIQUE,
    name                VARCHAR(150)    NOT NULL,
    description         TEXT,
    category_id         BIGINT          REFERENCES categories(id) ON DELETE SET NULL,
    supplier_id         BIGINT          REFERENCES suppliers(id) ON DELETE SET NULL,
    purchase_price      DECIMAL(12,2)   NOT NULL DEFAULT 0.00 CHECK (purchase_price >= 0),
    selling_price       DECIMAL(12,2)   NOT NULL CHECK (selling_price >= 0),
    current_stock       INTEGER         NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    minimum_stock_level INTEGER         NOT NULL DEFAULT 5 CHECK (minimum_stock_level >= 0),
    unit                VARCHAR(20)     NOT NULL DEFAULT 'pcs',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. INVENTORY TRANSACTIONS TABLE (Audit Trail / Stock Movement History)
CREATE TABLE IF NOT EXISTS inventory_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    transaction_type    VARCHAR(20)     NOT NULL, -- 'STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT'
    quantity            INTEGER         NOT NULL CHECK (quantity >= 0),
    unit_price          DECIMAL(12,2)   NOT NULL DEFAULT 0.00 CHECK (unit_price >= 0),
    previous_stock      INTEGER         NOT NULL CHECK (previous_stock >= 0),
    new_stock           INTEGER         NOT NULL CHECK (new_stock >= 0),
    reference_notes     TEXT,
    transaction_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Performance & Query Optimization Indexes
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_current_stock ON products(current_stock);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_product_id ON inventory_transactions(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_type ON inventory_transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_date ON inventory_transactions(transaction_date DESC);
